//created on: 2015/06/16
package com.example.order

rule "明細アップデート"
ruleflow-group "ヘッダ割引"
salience 1000
no-loop true

	when
		$detail : 注文明細()
	then
		update($detail);
end

rule "ヘッダ値引後金額設定"
ruleflow-group "ヘッダ割引"
salience 100
no-loop true

    when
        $header : 注文ヘッダ(明細合計金額 == "" , $注文番号 : 注文番号)
        $detail : 注文明細(注文番号 == $注文番号)
       
         // 注文番号単位の値引後金額合計をセット
		Number($明細合計金額 : longValue) from accumulate (注文明細(
											注文番号 == $注文番号, 
											$値引後金額 : 値引後金額) , sum((long)$値引後金額))
											
		$適用割引一覧 : List() from accumulate (注文明細(
											注文番号 == $注文番号, 
											$割引リスト : 適用割引一覧) ,collectList($割引リスト))
    then
        $header.set明細合計金額($明細合計金額);
        $header.get適用割引一覧().addAll($適用割引一覧);
   //     $header.set適用割引一覧($適用割引一覧);
    	System.out.println("*** " + $適用割引一覧 );   
   //     System.out.println("*** ルール名: " + kcontext.getRule().getName() +" *** ヘッダー行： " + $header.toString());
        update($header);
end

rule "合計金額算出"
ruleflow-group "ヘッダ割引"
salience -100
no-loop true

	when
		$header : 注文ヘッダ(合計金額 == "")
	then
		$header.set合計金額($header.get送料() + ( $header.get値引後金額() == 0 ? $header.get明細合計金額() : $header.get値引後金額()));
//        System.out.println("ヘッダ計算.drl ヘッダー行： " + $header.toString());
end